# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='county',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='postcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='town',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
