# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160309_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='contact',
            field=models.CharField(help_text='Provide a website, facebook group or email etc. where people can get more info', max_length=100),
        ),
    ]
