# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160311_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='address',
        ),
        migrations.RemoveField(
            model_name='events',
            name='country',
        ),
        migrations.RemoveField(
            model_name='events',
            name='county',
        ),
        migrations.RemoveField(
            model_name='events',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='events',
            name='town',
        ),
    ]
