# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160314_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
