# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160314_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrecurringdate',
            name='week_number',
            field=models.IntegerField(choices=[(1, '1st Week'), (2, '2nd Week'), (3, '3rd Week'), (4, '4th Week')]),
        ),
        migrations.AlterField(
            model_name='monthlyrecurringdate',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='weeklyrecurringdate',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
