# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-24 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20160316_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='info',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=9),
            preserve_default=False,
        ),
    ]
