# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-24 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20160324_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgames',
            name='eventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='events.Events'),
        ),
        migrations.AlterField(
            model_name='monthlyrecurringdate',
            name='eventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly', to='events.Events'),
        ),
        migrations.AlterField(
            model_name='onetimeeventdate',
            name='eventID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='onetime', serialize=False, to='events.Events'),
        ),
        migrations.AlterField(
            model_name='weeklyrecurringdate',
            name='eventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly', to='events.Events'),
        ),
    ]
